[Desktop Entry]
Type=X-GNOME-Metatheme
Name=Ambiance-Flat-zFusion-Blue-Spring-Pro
Comment=Ambiance Flat, A Redesigned Modern & Flat, Ambiance Based Theme W/New Colors By RAVEfinity.com (14.04)
Encoding=UTF-8

[X-GNOME-Metatheme]
GtkTheme=Ambiance-Flat-zFusion-Blue-Spring-Pro
MetacityTheme=Ambiance-Flat-zFusion-Blue-Spring-Pro
IconTheme=Vibrancy-Dark-Blue
CursorTheme=DMZ-White
ButtonLayout=close,minimize,maximize:
